config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  root "homes#top"

  resources :books, only: [:new, :create, :index, :show, :destroy] do

  resources :post_comments, only: [:create, :destroy]

  resource :favorites, only: [:create, :destroy]
  end


  get "/home/about" => "homes#about"



  resources :users
  resources :books


  #フォロー/フォロワー機能追加部分
  resources :users, only: [:index, :show, :edit, :update] do
# ——————————————— ここから ———————————————
  resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  get "relationships/followings"
# ——————————— ここまでネストさせる ———————————
end

#検索機能のルーティング
get 'search' => 'searches#search'

#DMのルーティング
get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum:2, maximum: 20}
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  
  #フォロー/フォロワー機能部分
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  
  has_many :followings, through: :relationships, source: :followed
  has_many :favorited_books, through: :favolites, source: :book
  
  
  attachment :profile_image
  
  #DM機能実装
  has_many :user_rooms
  has_many :chats
  
  
  #フォロー/フォロワー機能追加部分
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  
  #検索機能実装部分
  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
      elsif search == "backward_match"
        @user = User.where("name LIKE?","%#{word}")
        elsif search == "perfect_match"
          @user = User.where(name: word)
          elsif search == "partial_match"
            @user = User.where("name LIKE?","%#{word}%")
          else
            @user = User.all
          end
    
    
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_current_user, only: [:update]
  before_action :set_user, only: %I[show edit update destroy followings followers]
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
       render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end
  
  def followings
    @followings = @user.following_users
  end

  def followers
    @followers = @user.follower_users
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  
  

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def book_params
        params.require(:book).permit(:title, :body)
  end
  
  def  ensure_current_user
        @user = User.find(params[:id])
     if @user.id != current_user.id
        redirect_to user_path(current_user.id)

     end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<table class="table table-user">
  <h2>User info</h2>
  <thead>
    <tr>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>Introduction</th>
      <th><%= user.introduction %></th>
    </tr>

      <tr>
        <th>
          <%= link_to 'フォロー', user_followings_path(user.id) %>
          : <%= user.followings.count %>
        </th>
        </tr>
        <tr>
        <th>
          <%= link_to 'フォロワー', user_followers_path(user.id) %>
          : <%= user.followers.count %>
          </th>
          <th>
            <% if current_user != @user %>
              <%= link_to 'chatを始める', chat_path(@user.id)%>
            <% end %>
          </th>
      </tr>
    <tr>
      <th colspan="2">

      　<% if current_user == @user %>
        <%= link_to edit_user_path(@user), class:"btn btn-default btn-block" do %>
        <span class="fas fa-user-cog"></span>
      <% end %>

      <% else %>
        <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
      <% end %>
      <% end %>
      </th>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_for(@user) do |f| %>
<%= render 'books/error', model: @user %>

  <div class="user-name">Name</div>
    <%= f.text_field :name %>
    
  <div class="user-edit-image">Image</div>
    <%= f.attachment_field :profile_image %>
    
  <div class="form-body">Introduction</div>
    <%= f.text_area :introduction %>
    
  <div class="upload">
    <%= f.submit " Update User" %>
  </div>
  
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
  	  <table class="table table-sm user-index">
	  	  <h2>Users</h2>
        <thead>
          <th>image</th>
          <th>name</th>
          <th></th>
  	    </thead>
  	  	<tbody>
  	  	  <% @users.each do |user| %>
	  	  	<tr>
	  	  	  <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40,fallback: "no_image.jpg"%></td>
	  	  	  <td><%= user.name %></td>
	  	  	  
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
	  	  <td>
	  	  	  <% unless user. == @user %>
            <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
        <% end %>
        <% end %>
            </td>
	  	  	  
	  	  	  <td><%= link_to "Show", "/users/#{user.id}" %></td>
	  	  	</tr>
  	  	  <% end %>
  	  	</tbody>
  	  </table>
  	</div>
  </div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table table-user-show">
        <% @books.each do |book| %>
          <tr>
            
            <td>
              <a>
              <%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg"%>
              
            <% end %>
            </a>
            </td>
            
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>