config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  root "homes#top"

  resources :books, only: [:new, :create, :index, :show, :destroy] do

  resources :post_comments, only: [:create, :destroy]

  resource :favorites, only: [:create, :destroy]
  end


  get "/home/about" => "homes#about"



  resources :users
  resources :books


  #フォロー/フォロワー機能追加部分
  resources :users, only: [:index, :show, :edit, :update] do
# ——————————————— ここから ———————————————
  resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  get "relationships/followings"
# ——————————— ここまでネストさせる ———————————
end

#検索機能のルーティング
get 'search' => 'searches#search'

#DMのルーティング
get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  is_impressionable counter_cache: true

  belongs_to :user, optional: true
  attachment :profile_image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}



  #検索機能実装部分
def self.search(search, word)

  if search == "forward_match"
    @book = Book.where("title LIKE?","#{word}%")
  elsif search == "backward_match"
    @book = Book.where("title LIKE?","%#{word}")
  elsif search =="perfect_match"
    @book = Book.where(title: word)
  elsif search == "partial_match"
    @book = Book.where("title LIKE?","%#{word}%")
  else
    @book = Book.all
  end
end
#閲覧数カウント機能
def change
    add_column :books, :impressions_count, :integer, default: 0
end

end

app/models/chat.rb
class Chat < ApplicationRecord
  
   belongs_to :user
  belongs_to :room
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
  end
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book


end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum:2, maximum: 20}
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  
  #フォロー/フォロワー機能部分
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  
  has_many :followings, through: :relationships, source: :followed
  has_many :favorited_books, through: :favolites, source: :book
  
  
  attachment :profile_image
  
  #DM機能実装
  has_many :user_rooms
  has_many :chats
  
  
  #フォロー/フォロワー機能追加部分
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  
  #検索機能実装部分
  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
      elsif search == "backward_match"
        @user = User.where("name LIKE?","%#{word}")
        elsif search == "perfect_match"
          @user = User.where(name: word)
          elsif search == "partial_match"
            @user = User.where("name LIKE?","%#{word}%")
          else
            @user = User.all
          end
    
    
  end
  

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :correct_user, only: [:edit]
before_action :baria_user, only: [:edit, :update]

impressionist :actions=> [:show, :index]

  def correct_user
    book = Book.find(params[:id])
    if current_user.id != book.user_id
      redirect_to books_path
    end
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @post_comment = PostComment.new
    impressionist(@book, nil)
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
    #↑の@books=の記述はいいねの数を比較して多い順で表示している

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def baria_user
	unless Book.find(params[:id]).user.id.to_i == current_user.id
		redirect_to books_path
	end
    end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to request.referer
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<%= form_for(book) do |f| %>
  <div class="form-title row">
    <%= f.label :Title %>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="form-body row">
  	<%= f.label :Opinion %>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="actions row">
    <%= f.submit class: "btn btn-primary col-xs-12" %>
  </div>
<% end %>

app/views/books/_bookinfo.html.erb
<tr>
  <td>
    <%= link_to (book.user) do %>
    <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "noimage.jpg") %><br>
    <%= book.user.name %>
    <% end %>
  </td>

  <td><%= link_to book.title, book %></td>

  <td><%= book.body %></td>

  <td>
    <div id="favorite_btn_<%= book.id %>">
      <%= render 'favorites/favorite', {book: book} %>
    </div>
  </td>

  <td>コメント数：<%= book.book_comments.count %></td>

  <% if book.user == current_user %>
    <td><%= link_to "Edit",edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
    <td><%= link_to "Destroy",book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{book.id}" %></td>
  <% else %>
    <td colspan="2"></td>
  <% end %>
</tr>

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    
    
    <h1>Editing Book</h1>
      <%= render 'layouts/error', model: @book %>
      <%= render 'books/book', book: @book %>
    
    <div class="menu">
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
    </div>
  <div class="col-xs-3"></div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'books/error', model: @book %>
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <table class="table book-index">
        <h2>Books</h2>
        <thead>
          <th>Title</th>
          <th>Opinion</th>
        </thead>
        
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40,fallback: "no_image.jpg"%>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
              <td><%= book.body %></td>
              
              <td>
                <div id="favorite_btn_<%= book.id %>">
                <%= render 'favorites/favorite', {book: book} %>
              </div>
              </td>

  <td>コメント数：<%= book.post_comments.count %></td>
  
  <td>閲覧数：<%= book.impressionist_count %></td>

  <% if book.user == current_user %>
    <td><%= link_to "Edit",edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
    <td><%= link_to "Destroy",book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{book.id}" %></td>
  <% else %>
    <td colspan="2"></td>
  <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @newbook %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table table-user-show">
        <tr>
          <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg"%></td>
          <td><%= link_to @user.name, user_path(@user) %></td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <td>
    <div id="favorite_btn_<%= @book.id %>">
      <%= render 'favorites/favorite', {book: @book} %>
    </div>
      </td>
      
      <td>閲覧数：<%= @book.impressionist_count %></td>
      
          <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除しますか？"}, class:"btn btn-danger" %></td>
          <% end %>
        </tr>
        
        
        
      </table>
      <div class="comments">
<p>コメント件数：<%= @book.post_comments.count %></p>

</div>

<%= render 'post_comments/newform'%>

<h2>コメント</h2>

<div id = "comments_index"></div>
  <%= render 'post_comments/index', {book: @book, post_comments: @post_comments} %>

     </div>
    </div>
  </div>
</div>

app/views/chats/show.html.erb
<%= form_with model: @chat do |f| %>
    <%= f.text_field :message %>
    <%= f.hidden_field :room_id %>
    <%= f.submit %>
<% end %>
<table>
    <thead>
        <tr>
            <td>投稿者名</td>
            <td>投稿内容</td>
        </tr>
    </thead>
    <tbody>
        <% @chats.each do |chat| %>
            <tr>
                <td><%= chat.user.name %></td>
                <td><%= chat.message %></td>
            </tr>
        <% end %>
    </tbody>
</table>