config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  root "homes#top"

  resources :books, only: [:new, :create, :index, :show, :destroy] do

  resources :post_comments, only: [:create, :destroy]

  resource :favorites, only: [:create, :destroy]
  end


  get "/home/about" => "homes#about"



  resources :users
  resources :books


  #フォロー/フォロワー機能追加部分
  resources :users, only: [:index, :show, :edit, :update] do
# ——————————————— ここから ———————————————
  resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  get "relationships/followings"
# ——————————— ここまでネストさせる ———————————
end

#検索機能のルーティング
get 'search' => 'searches#search'

#DMのルーティング
get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  is_impressionable counter_cache: true

  belongs_to :user, optional: true
  attachment :profile_image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}



  #検索機能実装部分
def self.search(search, word)

  if search == "forward_match"
    @book = Book.where("title LIKE?","#{word}%")
  elsif search == "backward_match"
    @book = Book.where("title LIKE?","%#{word}")
  elsif search =="perfect_match"
    @book = Book.where(title: word)
  elsif search == "partial_match"
    @book = Book.where("title LIKE?","%#{word}%")
  else
    @book = Book.all
  end
end
#閲覧数カウント機能
def change
    add_column :books, :impressions_count, :integer, default: 0
end

end

app/models/chat.rb
class Chat < ApplicationRecord
  
   belongs_to :user
  belongs_to :room
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
  end
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book


end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum:2, maximum: 20}
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  
  #フォロー/フォロワー機能部分
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  
  has_many :followings, through: :relationships, source: :followed
  has_many :favorited_books, through: :favolites, source: :book
  
  
  attachment :profile_image
  
  #DM機能実装
  has_many :user_rooms
  has_many :chats
  
  
  #フォロー/フォロワー機能追加部分
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  
  #検索機能実装部分
  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
      elsif search == "backward_match"
        @user = User.where("name LIKE?","%#{word}")
        elsif search == "perfect_match"
          @user = User.where(name: word)
          elsif search == "partial_match"
            @user = User.where("name LIKE?","%#{word}%")
          else
            @user = User.all
          end
    
    
  end
  

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <script src="https://kit.fontawesome.com/951dfa5ed1.js" crossorigin="anonymous"></script>

    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="header">
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-left">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
            </a>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="">
                <%= link_to user_path(current_user), class:"btn btn-link" do %>
                <span class="fas fa-home"> Home</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to users_path, class:"btn btn-link" do %>
                <span class="fas fa-users"> Users</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to books_path, class:"btn btn-link" do %>
                <span class="fas fa-book-open"> Books</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to destroy_user_session_path, method: :delete, class:"btn btn-link" do %>
                <span class="fas fa-sign-out-alt"> Logout</span>
                <% end %>
              </li>
            <% else %>
              <li class="">
                <%= link_to root_path, class:"btn btn-link" do %>
                <span class="fas fa-home"> Home</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to home_about_path, class:"btn btn-link" do %>
                <span class="fas fa-link"> About</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to new_user_registration_path, class:"btn btn-link" do %>
                <span class="fas fa-user-plus"> sign up</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to new_user_session_path, class:"btn btn-link" do %>
                <span class="fas fa-sign-in-alt"> login</span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>




    <div class="body">

      <% if user_signed_in? %>

      <%= form_tag(search_path, method: :get) do %>
      
      <%= text_field_tag (:word) %>
      
      <%= select_tag 'range' ,options_for_select([['---選択してください---',''], ['User','1'], ['Book','2']]) %>

      <%= select_tag 'search', options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      
      <%= submit_tag "検索" %>

      <% end %>
      <% end %>

      <p class="notice"><%= notice %></p>

      <%= yield %>


        <footer>
          <p class="text-center"> CopyRight Infratop.inc</p>
        </footer>
      </div>
    </div>
  </body>
</html>